import type {AssetSet} from '../types/models';

export const assets: AssetSet = {
  splashBackground: require('./splash-background.png'),
  onboarding: {
    discover: require('./onboarding-discover.png'),
    pack: require('./onboarding-pack.png'),
    thrive: require('./onboarding-thrive.png'),
  },
  empty: require('./onboarding-pack-alt.png'),
  locations: {
    lakeBled: require('./location-lake-bled-forest-camp.png'),
    triglav: require('./location-triglav-valley-camp.png'),
    dolomites: require('./location-dolomites-alpine-camp.png'),
    blackForest: require('./location-black-forest-camp-trail.png'),
    plitvice: require('./location-plitvice-lakes-camp.png'),
    bohinj: require('./location-lake-bohinj-wild-camp.png'),
    highlands: require('./location-scottish-highlands-camp.png'),
    lofoten: require('./location-lofoten-coastal-camp.png'),
    pyrenees: require('./location-pyrenees-valley-camp.png'),
    annecy: require('./location-lake-annecy-camp-escape.png'),
    saxon: require('./location-saxon-switzerland-camp.png'),
    tatra: require('./location-tatra-mountain-camp.png'),
    lakeDistrict: require('./location-lake-district-camp-route.png'),
    madeira: require('./location-madeira-mountain-camp.png'),
    chamonix: require('./location-chamonix-alpine-camp.png'),
    garda: require('./location-lake-garda-camp-shore.png'),
    rila: require('./location-rila-lakes-camp-base.png'),
    berchtesgaden: require('./location-berchtesgaden-camp-valley.png'),
    picos: require('./location-picos-de-europa-camp.png'),
    hallstatt: require('./location-hallstatt-lake-camp.png'),
    vanoise: require('./location-vanoise-alpine-camp.png'),
    saimaa: require('./location-lake-saimaa-forest-camp.png'),
    ardennes: require('./location-ardennes-forest-camp.png'),
    tara: require('./location-tara-river-camp.png'),
    connemara: require('./location-connemara-wild-camp.png'),
    highTatras: require('./location-high-tatras-camp-trail.png'),
    oulanka: require('./location-oulanka-forest-camp.png'),
    lucerne: require('./location-lake-lucerne-camp.png'),
    aurlandsfjord: require('./location-aurlandsfjord-camp-view.png'),
  },
};
